第五章：Pandas入门

In [3]:
#Pandas数据结构
import numpy as np
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s)
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s)
print('--------------------')
print(s.values)#注意这里没有一对小括号
print(s.index)#注意这里没有一对小括号
# 和Series一样，values属性也会以ndarray的形式返回DF
print('和Series一样，values属性也会以ndarray的形式返回DF')
df = pd.DataFrame(np.arange(24).reshape(4,6))
print(df.values)
print(type(df.values))

print('可通过索引获取值')
print(s['a'])
print(s[['a','b','c']])#注意这里两层方括号

print('\n布尔，乘法，函数')
print(s[s>3])
print(s*10)
print(np.sqrt(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
--------------------
[1 2 3 4 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
和Series一样，values属性也会以ndarray的形式返回DF
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
<class 'numpy.ndarray'>
可通过索引获取值
1
a    1
b    2
c    3
dtype: int64

布尔，乘法，函数
d    4
e    5
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64
a    1.000000
b    1.414214
c    1.732051
d    2.000000
e    2.236068
dtype: float64


In [22]:
#是否存在
print('a' in s)
print('f' in s)
#通过字典创建Seris
s = pd.Series({'aa':11,'bb':22,'cc':33})
print(s)

print('-------------------------')
#Null值
s = pd.Series({'aa':11,'bb':22,'cc':np.nan})
print(s)
print(s.isnull())
print(s.notnull())

False
False
aa    11
bb    22
cc    33
dtype: int64
-------------------------
aa    11.0
bb    22.0
cc     NaN
dtype: float64
aa    False
bb    False
cc     True
dtype: bool
aa     True
bb     True
cc    False
dtype: bool


In [24]:
#Seris和其index都有name属性
s.name = 'qqqqq'
s.index.name  = 'wwwwww'
print(s)

wwwwww
aa    11.0
bb    22.0
cc     NaN
Name: qqqqq, dtype: float64


In [37]:
#DataFrame
#字典创建DataFrame
df = pd.DataFrame({'a':[1,2,3,4],'b':[1,2,3,4],'c':[1,2,3,4]})
print(df)
print('-------------------')
df = pd.DataFrame(np.arange(24).reshape(4,6),
                  columns=['a','b','c','d','e','f'])
print(df)
print(df['a'])#取某列
print('--------------------')
print(df.loc[2])#取某行

#通过赋值修改值
print('---------------------')
df['a'] = 100
print(df)

   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
-------------------
    a   b   c   d   e   f
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
0     0
1     6
2    12
3    18
Name: a, dtype: int32
--------------------
a    12
b    13
c    14
d    15
e    16
f    17
Name: 2, dtype: int32
---------------------
     a   b   c   d   e   f
0  100   1   2   3   4   5
1  100   7   8   9  10  11
2  100  13  14  15  16  17
3  100  19  20  21  22  23


In [43]:
#嵌套字典创建DF
# 内层键作为行索引
df = pd.DataFrame({'a':{1:1,2:2},'b':{1:1,2:2,3:3},'c':{1:1,2:2}})
print(df)
# 转置
print(df.T)

     a  b    c
1  1.0  1  1.0
2  2.0  2  2.0
3  NaN  3  NaN
     1    2    3
a  1.0  2.0  NaN
b  1.0  2.0  3.0
c  1.0  2.0  NaN


In [8]:
#索引对象
i = pd.Series(range(5),index = ['a','b','c','d','e'])
print(i.index)
print(i.index[1:3])#index有数组和集合的影子
'a' in i.index
#与python集合（set）不同的是，index可以有重复值

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Index(['b', 'c'], dtype='object')


True

In [20]:
#重建索引
s = pd.Series([1,2,3,4],index = ['a','b','c','d'])
print(s)
f = s.reindex(['a','b','c','d','e'])
print(f)
d = s.reindex(['a','b','c','d','e'],method = 'ffill')
print(d)
print('------------------------------')
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','b'],
                 columns = ['aa','bb','cc','dd'])
print(df)
print(df.reindex(['a','b','c'],['aa','bb']))
#简便做法
df.loc[['a','b','c'],['aa','bb']]

a    1
b    2
c    3
d    4
dtype: int64
a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64
a    1
b    2
c    3
d    4
e    4
dtype: int64
------------------------------
   aa  bb  cc  dd
a   0   1   2   3
b   4   5   6   7
    aa   bb
a  0.0  1.0
b  4.0  5.0
c  NaN  NaN


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Interpreting call
	'.reindex(a, b)' as 
	'.reindex(index=a, columns=b)'.
Use named arguments to remove any ambiguity. In the future, using positional arguments for 'index' or 'columns' will raise  a 'TypeError'.
  if sys.path[0] == '':
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  


aa   bb
a  0.0  1.0
b  4.0  5.0
c  NaN  NaN

In [23]:
#删除指定轴上的项
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','b'],
                 columns = ['aa','bb','cc','dd'])
print(df)
print(df.drop(['a'],axis = 'index'))

   aa  bb  cc  dd
a   0   1   2   3
b   4   5   6   7
   aa  bb  cc  dd
b   4   5   6   7


In [30]:
#索引，选择，过滤
#普通切片是左闭右开，Series是左闭右闭
s = pd.Series([1,2,3,4],index = ['a','b','c','d'])
print(s['b':'c'])

#loc和iloc
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','b'],
                 columns = ['aa','bb','cc','dd'])
print(df.loc['a',['aa','bb']])#轴标签
print(df.iloc[0,[0,1]])#整数标签
#轴标签还可以切片
print(df.loc[:,['aa','cc']])
print('--------------------')
s = pd.Series([1,2,3,4])
print(s.loc[:2])#右闭
print(s.iloc[:2])#右开


b    2
c    3
dtype: int64
aa    0
bb    1
Name: a, dtype: int32
aa    0
bb    1
Name: a, dtype: int32
   aa  cc
a   0   2
b   4   6
--------------------
0    1
1    2
2    3
dtype: int64
0    1
1    2
dtype: int64


In [33]:
#算数和数据对齐（pandas加减运算）
s1 = pd.Series([1,2,3,4],index = ['a','b','c','d'])
s2 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s1+s2)

df1 = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','b'],
                 columns = ['aa','bb','cc','dd'])
df2 = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','c'],
                 columns = ['aa','bb','ee','dd'])
print(df1+df2)
#除了交集区域，其他均为null
#add方法+填充缺失值
print('add方法+填充缺失值')
print(df1.add(df2,fill_value = 0))


a    2.0
b    4.0
c    6.0
d    8.0
e    NaN
dtype: float64
    aa   bb  cc   dd  ee
a  0.0  2.0 NaN  6.0 NaN
b  NaN  NaN NaN  NaN NaN
c  NaN  NaN NaN  NaN NaN
add方法+填充缺失值
    aa   bb   cc   dd   ee
a  0.0  2.0  2.0  6.0  2.0
b  4.0  5.0  6.0  7.0  NaN
c  4.0  5.0  NaN  7.0  6.0


In [49]:
#广播机制（DF-S）
#横着广播
arr = np.arange(12).reshape(3,4)
print(arr[0])
print('----------------')
print(arr-arr[0])

print('----------------')
df1 = pd.DataFrame(np.arange(8).reshape(2,4),index = ['a','b'],
                 columns = ['aa','bb','cc','dd'])
print(df1)
print(df1.iloc[0])
print(df1-df.iloc[0])

# 竖着广播
print('\n竖着广播')
s = df1['aa']
print(df1.sub(s,axis = 'index'))


[0 1 2 3]
----------------
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]
----------------
   aa  bb  cc  dd
a   0   1   2   3
b   4   5   6   7
aa    0
bb    1
cc    2
dd    3
Name: a, dtype: int32
   aa  bb  cc  dd
a   0   0   0   0
b   4   4   4   4

竖着广播
   aa  bb  cc  dd
a   0   1   2   3
b   0   1   2   3


In [57]:
#函数应用与映射
df = pd.DataFrame(np.random.randn(4,3))
print(df)
print(np.abs(df))#整个矩阵的绝对值
#apply方法
print('\n-----apply方法----\n')
f = lambda x: x.min() - x.max()
print(df.apply(f))#默认竖着
print(df.apply(f,axis = 'columns'))#横着

print('\n')
df = pd.DataFrame(np.random.randn(4,3),columns=['a','b','c'])
print(df)
def f(x):
    return pd.Series([x.min(),x.max()],index = ['min','max'])
df.apply(f)


          0         1         2
0 -0.905686  1.132575 -0.053979
1  1.569249 -0.973814  1.499774
2  0.532384  1.444126 -0.473399
3  0.938030  0.540886 -0.523488
          0         1         2
0  0.905686  1.132575  0.053979
1  1.569249  0.973814  1.499774
2  0.532384  1.444126  0.473399
3  0.938030  0.540886  0.523488

-----apply方法----

0   -2.474936
1   -2.417940
2   -2.023262
dtype: float64
0   -2.038262
1   -2.543063
2   -1.917524
3   -1.461517
dtype: float64


          a         b         c
0 -0.759830  0.075583  2.300389
1  1.236174  1.422535 -0.190231
2 -1.247125  0.374450 -0.456644
3 -0.029237  0.383400 -0.246822


a         b         c
min -1.247125  0.075583 -0.456644
max  1.236174  1.422535  2.300389

In [60]:
f = lambda x: '%0.2f' % x
print(df.applymap(f))
print(df['a'].apply(f))

       a     b      c
0  -0.76  0.08   2.30
1   1.24  1.42  -0.19
2  -1.25  0.37  -0.46
3  -0.03  0.38  -0.25
0    -0.76
1     1.24
2    -1.25
3    -0.03
Name: a, dtype: object


In [1]:
#排序与排名
import pandas as pd
import numpy as np
print('------------series-----------')
s = pd.Series([1,2,3,4],index = ['a','c','b','d'])
print(s)
print(s.sort_index())
print('\n-----------DataFrame------------')
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
print(df)
print('------------竖着-------------')
print(df.sort_index(axis = 0))#竖着
print('------------横着-------------')
print(df.sort_index(axis = 1))#横着
print('------------横着且降序-------------')
print(df.sort_index(axis = 1,ascending=False))
print('-----------对列中的值排序-------------')
print(df.sort_values(by = '1'))

------------series-----------
a    1
c    2
b    3
d    4
dtype: int64
a    1
b    3
c    2
d    4
dtype: int64

-----------DataFrame------------
   1  3  2  4
b  0  1  2  3
a  4  5  6  7
------------竖着-------------
   1  3  2  4
a  4  5  6  7
b  0  1  2  3
------------横着-------------
   1  2  3  4
b  0  2  1  3
a  4  6  5  7
------------横着且降序-------------
   4  3  2  1
b  3  1  2  0
a  7  5  6  4
-----------对列中的值排序-------------
   1  3  2  4
b  0  1  2  3
a  4  5  6  7


In [3]:
#rank
s = pd.Series([3,7,3,4],index = ['a','c','b','d'])
print(s.rank())#默认为method = avg
print(s.rank(method = 'first'))
print('-----------DataFrame-------------')
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
print(df.rank())
print(df.rank(axis = 1))

a    1.5
c    4.0
b    1.5
d    3.0
dtype: float64
a    1.0
c    4.0
b    2.0
d    3.0
dtype: float64
-----------DataFrame-------------
     1    3    2    4
b  1.0  1.0  1.0  1.0
a  2.0  2.0  2.0  2.0
     1    3    2    4
b  1.0  2.0  3.0  4.0
a  1.0  2.0  3.0  4.0


In [7]:
#带有重复值的轴索引
s = pd.Series([3,7,3,4],index = ['a','c','b','b'])
print(s.index.unique())
print(s['b'])
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
print(df.loc['a'])#DF的index索引只能用.loc()/.iloc()
print(df['1'])#字段索引没问题

Index(['a', 'c', 'b'], dtype='object')
b    3
b    4
dtype: int64
1    4
3    5
2    6
4    7
Name: a, dtype: int32
b    0
a    4
Name: 1, dtype: int32


In [3]:
#数据汇总和描述
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
print(df)
print(df.sum())#竖着
print(df.sum(axis = 1))#横着
#describe（）和value_counts(),isin()
print('-----------apply()和value_counts()-----------')
df = pd.DataFrame({'q1':[1,2,2,1,2],
                 'q2':[3,3,4,5,5],
                  'q3':[3,3,2,1,2]})
print(df)
print(df.apply(pd.value_counts).fillna(0))#有问题

   1  3  2  4
b  0  1  2  3
a  4  5  6  7
1     4
3     6
2     8
4    10
dtype: int64
b     6
a    22
dtype: int64
-----------apply()和value_counts()-----------
   q1  q2  q3
0   1   3   3
1   2   3   3
2   2   4   2
3   1   5   1
4   2   5   2
    q1   q2   q3
1  2.0  0.0  1.0
2  3.0  0.0  2.0
3  0.0  2.0  2.0
4  0.0  1.0  0.0
5  0.0  2.0  0.0


In [ ]:
#相关系数与协方差


In [47]:
#缺失值过滤
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
print(df)
df.loc['a','3'] = np.nan
print(df[df.notnull()])#有问题
#df.dropna()
print('\n---------df.dropna()---------')
print(df.dropna())
print('\n')
print(df.dropna(how = 'all'))

   1  3  2  4
b  0  1  2  3
a  4  5  6  7
   1    3  2  4
b  0  1.0  2  3
a  4  NaN  6  7

---------df.dropna()---------
   1    3  2  4
b  0  1.0  2  3


   1    3  2  4
b  0  1.0  2  3
a  4  NaN  6  7


In [11]:
#填充缺失数据
df = pd.DataFrame(np.arange(8).reshape(2,4),index = ['b','a'],
                 columns = ['1','3','2','4'])
df['2'] = np.nan
df.loc['a','3'] = np.nan
print(df)
print(df.fillna(0))
print('-------字典填充-------')
print(df.fillna({'2':111,'a':'0'}))#只能针对为null值的，进行填充
#inplace = True,修改源df
print(df.fillna(df.mean()))#这里算出了每个字段的均值，然后这个字段如果
#有缺失值，就用它填充，这里的字段‘2’全部为null，所以填充值也为null
print(df.fillna(df['4'].mean()))#这样就不行了，这种方法好像只能用Seris
df.mean()

   1    3   2  4
b  0  1.0 NaN  3
a  4  NaN NaN  7
   1    3    2  4
b  0  1.0  0.0  3
a  4  0.0  0.0  7
-------字典填充-------
   1    3      2  4
b  0  1.0  111.0  3
a  4  NaN  111.0  7
   1    3   2  4
b  0  1.0 NaN  3
a  4  1.0 NaN  7
   1    3    2  4
b  0  1.0  5.0  3
a  4  5.0  5.0  7


1    2.0
3    1.0
2    NaN
4    5.0
dtype: float64

In [68]:
#层次化索引
s = pd.Series(np.random.randn(10),
              index = [['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
print(s)
print(s.index)#这里居然不是元组了
print(s[:,2])#外索引，内索引都可以用

print('-----------重新生成一个DataFrame------------')
print(s.unstack())

a  1    0.753762
   2    2.229193
   3   -0.388695
b  1   -2.064985
   2   -1.268953
   3   -1.445640
c  1   -0.836296
   2   -0.734389
d  2   -1.465162
   3    0.643286
dtype: float64
MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])
a    2.229193
b   -1.268953
c   -0.734389
d   -1.465162
dtype: float64
-----------重新生成一个DataFrame------------
          1         2         3
a  0.753762  2.229193 -0.388695
b -2.064985 -1.268953 -1.445640
c -0.836296 -0.734389       NaN
d       NaN -1.465162  0.643286


In [ ]:
#重新分级排序


第六章：数据载入，存储，及文件格式

In [20]:
df = pd.read_csv(r'C:\Users\123\Desktop\ex1.csv')
print(df)
#也可以用read_table()
df = pd.read_table(r'C:\Users\123\Desktop\ex1.csv',sep = ',')
print(df)
#不要表头
print('\n--------不要表头-----------')
df = pd.read_csv(r'C:\Users\123\Desktop\ex1.csv',header = None)
print(df)
print('\n--------表头names-----------')
#指定message这列为索引
names = ['a','b','c','d','message']
df = pd.read_csv(r'C:\Users\123\Desktop\ex1.csv',
                names = names,index_col = 'message')
print(df)


   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

--------不要表头-----------
   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

--------表头names-----------
         a   b   c   d
message               
message  a   b   c   d
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12


In [22]:
df = pd.read_csv(r'C:\Users\123\Desktop\csv_mindex.csv')
print(df)
#分层索引
df = pd.read_csv(r'C:\Users\123\Desktop\csv_mindex.csv',
                index_col = ['key1','key2'])
print(df)


  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16
           value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16


In [23]:
#利用正则表达式
#\s+表示匹配一个或多个空格
df = pd.read_table(r'C:\Users\123\Desktop\ex3.txt',sep = '\s+')
print(df)

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491


In [26]:
df = pd.read_csv(r'C:\Users\123\Desktop\ex4.csv')
print(df)
#skiprows参数，跳过特定行
df = pd.read_csv(r'C:\Users\123\Desktop\ex4.csv',skiprows = [0,2,3])
print(df)

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


In [27]:
#缺失值
df = pd.read_csv(r'C:\Users\123\Desktop\ex5.csv')
print(df)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


In [34]:
#分块读入文本文件
pd.options.display.max_rows = 10#只显示十条数据
df = pd.read_csv(r'C:\Users\123\Desktop\ex6.csv')
print(df)
#用nrow显示前五行
df = pd.read_csv(r'C:\Users\123\Desktop\ex6.csv',nrows = 5)
print(df)
#用head显示前五行
df = pd.read_csv(r'C:\Users\123\Desktop\ex6.csv')
print(df.head())
print(df['key'].value_counts().head(10))

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]
        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404

In [38]:
#将数据写入文本格式
#到处csv
df = pd.read_csv(r'C:\Users\123\Desktop\ex5.csv')
df.to_csv(r'C:\Users\123\Desktop\out.csv')
import sys
df.to_csv(r'C:\Users\123\Desktop\out.csv',sep = '|')
#将缺失值显示为null
df.to_csv(r'C:\Users\123\Desktop\out.csv',sep = '|',na_rep = 'null')
#from_csv()

In [6]:
#使用分隔格式
import csv
f = open(r'C:\Users\123\Desktop\ex1.csv')
df = csv.reader(f)
print(df)
for i in df:
    print(i)

['a', 'b', 'c', 'd', 'message']
['1', '2', '3', '4', 'hello']
['5', '6', '7', '8', 'world']
['9', '10', '11', '12', 'foo']


In [7]:
#XML和HTML
from lxml.html import parse
from urllib2 import urlopen
parsed = parse(urlopen('http://b.appindata.com/#/manage/mobile_call_history'))
doc = parsed.getroot()

ModuleNotFoundError: No module named 'urllib2'

In [10]:
#二进制数据格式（pickle）
f = pd.read_csv(r'C:\Users\123\Desktop\ex1.csv')
print(f)
f.save(r'C:\Users\123\Desktop\ex1.pkl')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


AttributeError: 'DataFrame' object has no attribute 'save'