第八章：数据规整化，清理，转换，合并，重塑

In [9]:
#重排列和层次排序
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
print(frame)
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
#swapelevel()改变索引层次
print('\n---------源frame---------')
print(frame)
print('\n---------level = 1---------')
print(frame.sort_index(level = 1))
print('\n---------level = 1---------')
print(frame.sort_index(level = 0))

frame.swaplevel('key1','key2')#不知道有什么作用


     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

---------源frame---------
state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

---------level = 1---------
state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

---------level = 1---------
state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [16]:
#按层级进行汇总统计
print(frame.sum(level = 'key2'))
print(frame.sum(level = 1))
#level = 'key2'等价于level = 1
print(frame.sum(level = 'color',axis = 1))#去掉axis = 1就报错，
# 因为level只能是Index,不能是column  
 

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16
state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16
color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10


In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})
print(df1)
print(df2)
print('\n--------merge()--------')
print(pd.merge(df1,df2))
print('\n--------外连接--------')
print(pd.merge(df1,df2,how = 'outer'))#外连接
print('\n--------左连接--------')
print(pd.merge(df1,df2,how = 'left'))#左连接
print('\n--------内连接--------')
print(pd.merge(df1,df2,on = 'key'))#指定聚合键


  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

--------merge()--------
  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

--------外连接--------
  key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

--------左连接--------
  key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

--------内连接--------
  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0


In [19]:
#使用df的列进行索引(把某一列变成索引)
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two',
                            'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})
print(frame)
print(frame.set_index(['c','d']))
print(frame.reset_index())

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3
       a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1
   index  a  b    c  d
0      0  0  7  one  0
1      1  1  6  one  1
2      2  2  5  one  2
3      3  3  4  two  0
4      4  4  3  two  1
5      5  5  2  two  2
6      6  6  1  two  3


In [16]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})
print(pd.merge(df3,df4,left_on = 'lkey',right_on = 'rkey'))
# print(pd.merge(df3,df4,left_index = True))


  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0


In [23]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
print(left)
print(right)
print('\n-------------inner(交集)-------------')
print(pd.merge(left,right,on = ['key1','key2']))
print('\n-------------outer(补集)-------------')
print(pd.merge(left,right,on = ['key1','key2'],how = 'outer'))
print('------------suffixes打左右标签-------------')
print(pd.merge(left,right,on = 'key1'))
print(pd.merge(left,right,on = 'key1',suffixes = ['_left','_right']))

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

-------------inner(交集)-------------
  key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

-------------outer(补集)-------------
  key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0
------------suffixes打左右标签-------------
  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7
  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       o

In [26]:
#索引上的合并
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
print(left1)
print(right1)
print(pd.merge(left1,right1,left_on = 'key',right_index = True))

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0
  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0


In [3]:
#层次化索引
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio',
                               'Nevada', 'Nevada'],
                      'key2': [2000, 2001, 2002, 2001, 2002],
                      'data': np.arange(5.)})
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                      index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',
                              'Ohio', 'Ohio'],
                             [2001, 2000, 2000, 2000, 2001, 2002]],
                      columns=['event1', 'event2'])
print(lefth)
print(righth)
#以列表的形式
print(pd.merge(lefth,righth,left_on = ['key1','key2'],right_index = True))

print('------------同时使用双方的索引------------')
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama'])
print(pd.merge(left2,right2,left_index = True,right_index = True))

     key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0
             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11
     key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1
------------同时使用双方的索引------------
   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0


In [6]:
#join实例方法
print(left2.join(right2,how = 'outer'))

another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=['a', 'c', 'e', 'f'],
                       columns=['New York', 'Oregon'])
print(another)
print('\n--------三表连接-------')
print(left2.join([right2,another]))#注意这里为中括号
print(left2.join([right2,another],how = 'outer'))

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0
   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

--------三表连接-------
   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0
   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0


D:\anaconda3\lib\site-packages\pandas\core\frame.py:6369: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  verify_integrity=True)


In [4]:
#轴向连接（连接，绑定，堆叠）
#numpy数组
print('------numpy数组-----')
arr = np.arange(12).reshape(3,4)
print(arr)
print(np.concatenate([arr,arr],axis = 1))#横向拼接
print(np.concatenate([arr,arr]))#纵向堆叠

#series
print('\n--------series--------')
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
print(pd.concat([s1,s2,s3]))#横向
print(pd.concat([s1,s2,s3],axis = 1))#纵向


------numpy数组-----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

--------series--------
a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  from ipykernel import kernelapp as app


     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [7]:
s4 = pd.concat([s1*5,s3])
print('-------s4------')
print(s4)
print('------s1------')
print(s1)
print(pd.concat([s1,s4],axis = 1))#默认为‘outer’
print(pd.concat([s1,s4],axis = 1,join = 'inner'))#注意这里是join不是how
print(pd.concat([s1,s4],axis = 1,join = 'inner',
               join_axes = [['a','b','c','d']]))#注意这里是两个方括号
#join_axes只能给一个参数，这里这个参数是列表['a','b','c','d']

-------s4------
a    0
b    5
f    5
g    6
dtype: int64
------s1------
a    0
b    1
dtype: int64
     0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6
   0  1
a  0  0
b  1  5
     0    1
a  0.0  0.0
b  1.0  5.0
c  NaN  NaN
d  NaN  NaN


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [27]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
print(s1)
print(s2)
print(s3)
#堆叠时增加层次化索引
print('\n-----------堆叠时增加层次化索引----------')
r = pd.concat([s1,s2,s3],keys = ['one','two','three'])
print(r)
#沿着axis = 0对series进行堆叠，keys就会成为series的索引
#沿着axis = 1对series进行堆叠，keys就会成为DF的表头
print(pd.concat([s1,s2,s3],axis = 1,keys = ['one','two','three']))

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64

-----------堆叠时增加层次化索引----------
one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64
   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]


In [26]:
#unstack函数
print(r.unstack())


         a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0


In [31]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])
print(df1)
print(df2)
print(pd.concat([df1,df2],axis = 1,keys = ['level1','level2']))
#可传入一个字典,主键就是keys的值
print(pd.concat({'level1':df1,'level2':df2},axis = 1))
#为层次化索引命名
pd.concat([df1,df2],axis = 1,keys = ['level1','level2'],
         names = ['upper','lower'])

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      5     6
c      7     8
  level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0
  level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  import sys
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if sys.

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [36]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(df1)
print(df2)
#不保留连接轴上的索引
print('\n')
print(pd.concat([df1,df2]))
print(pd.concat([df1,df2],ignore_index = True))
#注意这里的索引

          a         b         c         d
0 -1.066409 -0.979210 -0.653102  1.260708
1  1.236856 -0.306671  1.433421 -1.651843
2 -0.385778  0.397144  0.756325 -2.398808
          b         d         a
0  1.346467 -1.468993 -2.037515
1  0.619970  1.142554  0.514385


          a         b         c         d
0 -1.066409 -0.979210 -0.653102  1.260708
1  1.236856 -0.306671  1.433421 -1.651843
2 -0.385778  0.397144  0.756325 -2.398808
0 -2.037515  1.346467       NaN -1.468993
1  0.514385  0.619970       NaN  1.142554
          a         b         c         d
0 -1.066409 -0.979210 -0.653102  1.260708
1  1.236856 -0.306671  1.433421 -1.651843
2 -0.385778  0.397144  0.756325 -2.398808
3 -2.037515  1.346467       NaN -1.468993
4  0.514385  0.619970       NaN  1.142554


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  import sys
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [43]:
#合并重叠数据
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e', 'd', 'c', 'b', 'a'])
print(a)
print(b)
b[-1] = np.nan
#使用np.where()
print(np.where(pd.isnull(a),b,a))
#使用combine_first()自己有的用自己的，没有的combine_first别人的
#就是打补丁
print('--------combine_first---------')
print(b[:-2])
print(a[2:])
print('\n-----------------')
print(b[:-2].combine_first(a[2:]))

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64
[0.  2.5 2.  3.5 4.5 nan]
--------combine_first---------
f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

-----------------
a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64


In [44]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                    'b': [np.nan, 2., np.nan, 6.],
                    'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                    'b': [np.nan, 3., 4., 6., 8.]})
print(df1)
print(df2)
print(df1.combine_first(df2))

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14
     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0
     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN


In [3]:
#重塑（reshape）和轴向旋转(pivot)
# stack（将横着的转为竖着的）
# unstack（将竖着的转为横着的）

data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                    name='number'))
print(data)
print('------------------')
print(data.stack())
print(data.stack().unstack())

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5
------------------
state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32
number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5


In [4]:
import pandas as pd
import numpy as np
print(data.stack().unstack(0))#0为层级，-1为最内层，0为最外层，默认为-1
print(data.stack().unstack('state'))#可直接指定层级名称

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5
state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5


In [14]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
print(data2)
print(data2.unstack())
print(data2.unstack().stack())#可逆的
print(data2.unstack().stack(dropna = False))#dropna默认为true，
# 表示自动去除null值，dropna = False为保留null值

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64
       a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0
one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64
one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64


In [18]:
result = data.stack()
df = pd.DataFrame({'left': result, 'right': result + 5},
                  columns=pd.Index(['left', 'right'], name='side'))
print(df)
print('\n--------------------')
print(df.unstack('state').stack('side'))

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

--------------------
state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7


In [33]:
# 将长透视为宽
data = pd.read_csv(r'C:\Users\123\Desktop\macrodata.csv')
print(data.head())
periods = pd.PeriodIndex(year = data.year,quarter = data.quarter,
                     name = 'data')
print('\n-------------------------')
print(periods)
print('\n------------------------')
columns = pd.Index(['realgdp','infl','unemp'],name = 'item')
data = data.reindex(columns = columns)
data.index = periods.to_timestamp('D','end')
print(data.head())
ldata = data.stack().reset_index().rename(columns = {0:'value'})
print(ldata.head())

     year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19  

-------------------------
PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2

In [35]:
#pivot方法
pivoted = ldata.pivot('data','item','value')
print(pivoted.head())
#data对应index,value对应columns

item        infl   realgdp  unemp
data                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
1959-09-30  2.74  2775.488    5.3
1959-12-31  0.27  2785.204    5.6
1960-03-31  2.31  2847.699    5.2


In [52]:
ldata['value2'] = np.random.randn(len(ldata))
print(ldata.head())
print('-------------目标------------')
pivoted = ldata.pivot('data','item')#横轴data,纵轴item
print(pivoted.head())
print(pivoted['value'][:5])
print(pivoted['value2'][:5])

print('-----------------------')
unstack = ldata.set_index(['data','item']).unstack('item')
print(unstack.head())

        data     item     value    value2
0 1959-03-31  realgdp  2710.349 -0.666375
1 1959-03-31     infl     0.000 -1.229429
2 1959-03-31    unemp     5.800  0.052037
3 1959-06-30  realgdp  2778.801  0.729766
4 1959-06-30     infl     2.340 -1.460734
-------------目标------------
           value                    value2                    
item        infl   realgdp unemp      infl   realgdp     unemp
data                                                          
1959-03-31  0.00  2710.349   5.8 -1.229429 -0.666375  0.052037
1959-06-30  2.34  2778.801   5.1 -1.460734  0.729766 -0.276175
1959-09-30  2.74  2775.488   5.3 -0.183625  0.781089 -0.326300
1959-12-31  0.27  2785.204   5.6 -1.372156 -0.581055 -1.998103
1960-03-31  2.31  2847.699   5.2  0.139445 -0.307979  0.734998
item        infl   realgdp  unemp
data                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
1959-09-30  2.74  2775.488    5.3
1959-12-31  0.27  2785.204    5.6
1960-03-31  

In [17]:
#将宽透视为长
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                   'A': [1, 2, 3],
                   'B': [4, 5, 6],
                   'C': [7, 8, 9]})
print(df)
#id_vars指定列进行unpivot操作(有id的意思)
# id_vars对应index，value_vars对应columns!!!!!
melted = pd.melt(df,id_vars='key')
print(melted)
print(melted.pivot('key','variable','value'))
pd.melt(df,value_vars=['A','B','C'])

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9
   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9
variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7


variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9